---
letsencrypt_vars:
  package:  'certbot'
  bin_path: '/usr/bin/letsencrypt'
  conf_dir: '/etc/certbot'
  work_dir: '/var/lib/certbot'
  log_dir:  '/var/log/certbot'
  owner:    'root'
  group:    'root'
